### ISSUE TITLE
Other country codes

### ISSUE THREAD

**Issue by Vanuan** [lang-uk/ua-gazetteers#1]
Here's a dataset which contains the same 3166 codes in English and French:
https://github.com/datasets/country-codes/blob/master/data/country-codes.csv

They're parsing it directly from ISO.org: https://github.com/datasets/country-codes/blob/master/scripts/get_countries_of_earth.py

**Comment by dchaplinsky** [comment]
Where is Ukrainian translation? :)

**Comment by Vanuan** [comment]
You can submit a PR, since pull from ISO is not supported anymore https://github.com/datasets/country-codes/issues/20  :)

Some other interesting datasets:
https://github.com/datasets/registry/blob/master/core-list.txt
